### ISSUE TITLE
"parse configure token" no longer works

### ISSUE THREAD

**Issue by okofish** [ParsePlatform/parse-cli#12]
I suppose this is actually an issue with the Parse site, but the URL "parse configure token" redirects to, "https://www.parse.com/account/account_keys", now returns a 404 error.

**Comment by pavanka** [comment]
sorry, it was supposed to be in pre-release.
this feature is not released yet. will be released real soon though!

**Comment by okofish** [comment]
Ok, thanks. Can't wait!
