### ISSUE TITLE
Push Settings & Parameters

### ISSUE THREAD

**Issue by ophirharpaz** [ParsePlatform/parse-cli#16]
Hello,
First of all thank you for this tool. I'm looking forward to its developments, and I know for sure it will make my work easier... :)

I was wondering...
* Would you enable passing parameters to the various functions, in order to allow automating processes? (For example, passing username, password and app name to `$ parse new`)
* Do you think it'd be possible to add an option of uploading a `.p12` file to an existing app, in order to enable push messages?

Thank again for your new tool! :+1:

**Comment by pavanka** [comment]
I am curious why you would want to automatically create new apps?
that is not recommended. but we could definitely allow for passing params as options instead.

* very soon you would not need to provide username/password instead you can configure personal dev access tokens & cli will automatically pick them up.
* I am not sure about uploading .p12 files, thought it is not in roadmap for immediate future, I do think down the line, that should be possible.

thanks for the feedback. I'll keep you posted.

**Comment by mortenholmgaard** [comment]
I would be interrested in exactly the same as @ophirharpaz to create app and setup them for push. When you have a lot of apps like I do, it would be nice to be able to automate it.

**Comment by pavanka** [comment]
@ophirharpaz, @mortenholmgaard would you mind listing out the required features, and an example use case where this makes your life easy. (like which commands would you like to accept flags in addition to being interactive). I'll flush it out over the weekend. 

I was working on: [account keys](https://parse.com/docs/js/guide#command-line-account-keys) the past few days and did not get time to work on other things, sorry for the delay.

**Comment by mortenholmgaard** [comment]
Our wishes are quite simple for a start at least: (core features)
Create app: Provide a name and it should return all keys.
Upload certificates file: (add/replace based on bundle identifier)

Usecase: 
A customer is requesting/creating an app at our website and setup all content, including publishing text. Then when we have to build and publish the apps we can automate most of it with Fastlane, and then it could be nice to be able to automate the Parse push setup as well from a bash script or similar. When we have a lot of apps to publish automation make life a lot easier.

**Comment by pavanka** [comment]
you can already create a new app & list its properties. but yeah that is a bit obscured out, this was done to be backward compatible.

parse new lets you create an app.
parse list lets you view properties of an app.

both of the use the [apps API](https://parse.com/docs/rest/guide#apps)
you can use the apps api in your automation scripts also [this](http://blog.parse.com/announcements/introducing-account-keys-better-authentication-for-the-command-line-tool/) might be helpful.

I'll discuss about the second use case [upload certs] and get back soon.

**Comment by pavanka** [comment]
btw even if the cli is interactive you can still pass around parameters using os piping
example repo: https://github.com/pavanka/travis-hello/

however, it is not guaranteed that inputs order will remain the same.

**Comment by mortenholmgaard** [comment]
@pavanka 
Thanks
Any news regarding upload certs?

**Comment by pavanka** [comment]
hey, so u can build from master and see that 'new' has been parametrized.
pl try it out and let me know.

uploading certs for push is not supported by the api so cli cannot do that. however, I will talk to the relevant team and get back to you to see if they want to support such an api.

**Comment by pavanka** [comment]
@mortenholmgaard @ophirharpaz
The push team prefers the current approach and does not favor building a new endpoint.
@bnham can comment with more details.
