### ISSUE TITLE
behind corporate proxy

### ISSUE THREAD

**Issue by behboud** [ParsePlatform/parse-cli#19]
Hi
Is it possible to set a http proxy? I use parse behind a proxy and it outputs
```
Error talking to the Parse servers; please try again.
```

**Comment by pavanka** [comment]
we use standard go http transport.
https://golang.org/src/net/http/transport.go says that 

<code>
  // ProxyFromEnvironment returns the URL of the proxy to use for a given request, as indicated by the environment variables.

  // HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof). HTTPS_PROXY takes precedence over HTTP_PROXY for https requests.
</code>


can you try by setting these env vars
HTTP_PROXY & HTTPS_PROXY and try to use the cli. Let me know what you find.

**Comment by behboud** [comment]
I'm on Windows. I set the env and get the proxy via echo. But still no luck talking to parse server. Any option I can set or log file I can find and send you?

**Comment by behboud** [comment]
seems I used the wron Windows binary. When I googled I came along this post:
http://blog.parse.com/announcements/parse-command-line-tools-available-for-windows/
which seems to be old.
It worked when I changed to this:
https://parse.com/downloads/cloud_code/cli/parse-windows/latest

**Comment by pavanka** [comment]
great, I was clueless as to why it does not work for you. it worked for me when I tested on windows, linux & mac behind a firewall.

for future reference: you can download required binaries from here
https://github.com/ParsePlatform/parse-cli/releases
