### ISSUE TITLE
deploy and ignore certain files

### ISSUE THREAD

**Issue by XoniycL** [ParsePlatform/parse-cli#20]
When deploying files to the cloud, will there be any plan to ignore certain ones?
like .gitignore

**Comment by pavanka** [comment]
there is already one :)
I'll update the docs in a while. 

You can add rules to a .parseignore file to ignore certain files.
it implements a subset of .gitignore rules: see
https://github.com/ParsePlatform/parse-cli/blob/master/parseignore.go
and https://github.com/facebookgo/parseignore for more details

**Comment by XoniycL** [comment]
Awesome ~ :)
really useful !!
Thanks you :+1:
