### ISSUE TITLE
v2.2.5 "parse releases" broken

### ISSUE THREAD

**Issue by robertjustjones** [ParsePlatform/parse-cli#29]
I'm suddenly getting the following
```
$ parse releases
json: cannot unmarshal string into Go value of type main.deployFileData

$ parse help
Parse Command Line Interface
Version 2.2.5
```

**Comment by pavanka** [comment]
yup we got a bug report. fixed in master. 
https://github.com/ParsePlatform/parse-cli/commit/b7f3c2bfddf153e2e412606efdc3f15120fe0093

I'll make a release end of this week.
