### ISSUE TITLE
Ability to call cloud function

### ISSUE THREAD

**Issue by OdNairy** [ParsePlatform/parse-cli#31]
It would be very nice to have a way call custom cloud functions by parse-cli. As well as some keys are needed we can configure them in `parse configure`.

**Comment by pavanka** [comment]
Why do you need parse configure to configure keys
Pretty much anything you want to do can be done with an "account key" & the app name, 

I feel that there is no nice way of calling functions
parse run --app "MyParseApp" myfunction -d "{'param1': 'value1',...}"
does not seem that neat to me. Do you have ideas on how to pass parameters to the function.

**Comment by pavanka** [comment]
I am up for 
parse run --app "appname" --function "functionname"

and parameters read from input stream
so you can pipe them like

cat parameters.json| parse run ....
or just type 
parse run...
and type in parameters in the stdin

please re-open if you have more suggestions please comment. also I am not sure how valuable this feature is, so closing out. if there is enough interest I can do it.
