### ISSUE TITLE
Continuous Deployment to parse: how can I make everything automatic on Travis CI?

### ISSUE THREAD

**Issue by AFusco** [ParsePlatform/parse-cli#32]
I want to set automatic deployment whenever I push my repo to github. 
Parse-cli stalls the deploy because it doesn't have any configuration on the Travis-CI VM, so it waits for the user-email to be submitted.

Is there any workaround to this? Is there a way to provide all the information needed as arguments? Or maybe a way to create all the configuration files needed so that parse-cli thinks it has already been configured?

Any help is appreciated, thank you in advance!

**Comment by pavanka** [comment]
You can add a master key in the config, for travis-ci to work.

I am not sure how your config file looks like. I can help you, if you can share a private gist with me.

**Comment by AFusco** [comment]
No need to make it private!

```
language: node_js
node_js:
  - "0.12"
install: 
  - mkdir $HOME/parse/bin;
  - wget https://github.com/ParsePlatform/parse-cli/releases/download/release_2.2.6/parse_linux -O $HOME/parse/bin/parse
  - chmod +x $HOME/parse/bin/parse
  - export PATH=$PATH:$HOME/parse/bin/parse
script: echo 'deploying...' 
after_success: parse deploy

```

Here's what I tried to do: I tried to create a $HOME/.parse/netrc file with a key, but it didn't work, so I tried to create a config/global.json file but that failed too.

**Comment by pavanka** [comment]
So, you can set master key in your config/global.json

for instance

```json
{
  "applications": {
    "_default": {
      "link": "hello"
    },
    "hello": {
      "applicationId": "xxxxx..",
      "masterKey" : "xxxxx.."
    }
  }
}
```json

**Comment by AFusco** [comment]
Has the `config/global.json` file the same structure as the `.parse.local` file?

**Comment by pavanka** [comment]
`config/global.json` is less preferred, `.parse.local` file should be used instead.
looking at your file structure would help.

also in the travis script: you should not download a fixed version of cli instead this is a better approach

```bash
curl -s https://www.parse.com/downloads/cloud_code/installer.sh | sudo /bin/bash
```

This would ensure you download the latest version always.

`deploy_cmd.go` has the functionality for the parse deploy endpoints, we could mimic that functionality, to get travis-ci deploy.

ideally one would provide an account key [like an aws secret] in the travis script,
which can then be used to set account key in pre-deploy, and you just have to do `parse-cli deploy`

**Comment by pavanka** [comment]
assuming it is resolved for u.

**Comment by pavanka** [comment]
I created an example of how to use travis-ci and account key to achieve the same.
You can see it here: https://github.com/pavanka/travis-hello
And a travis build that pushes to parse is here: https://travis-ci.org/pavanka/travis-hello/builds/80049941

Note that your account key needs to be private. so add it using travis encrypt like

`travis encrypt ACCOUNT_KEY=${your_account_key} --add`

**Comment by AFusco** [comment]
That is exactly what I was looking for. Thank you very much.
Your solution is much cleaner than what I came up with.

**Comment by ishanstealth18** [comment]
Hii,

I am getting parsing error though my YML file is correct, any solutions?

**Comment by pavanka** [comment]
Hi @ishanstealth18,
Parse has shutdown, so we do not have the api-servers which parse-cli uses.

Please read:
http://blog.parse.com/announcements/moving-on/
Unfortunately, the cli would not work at this point, just like the rest of Parse [dashboard, data, etc.]

**Comment by ishanstealth18** [comment]
What is an alternate solution?

**Comment by ericnakagawa** [comment]
@ishanstealth18 Spin up an instance running https://github.com/ParsePlatform/parse-server , you'll also need a mongo database. You can run this locally to try it out.

**Comment by ishanstealth18** [comment]
okk. but when i tried to do git push it was giving permission denied..
