### ISSUE TITLE
Choosing accountkey when using "parse new" command

### ISSUE THREAD

**Issue by Ralphilius** [ParsePlatform/parse-cli#39]
Hello,

I have a situation when there are 2 account keys in my laptop. One is set as default. I want to do "parse new" to fetch the cloud code from the other account to local. Is there any way that I can choose the account key from the other account?

I have tried `cmd /C "set PARSER_EMAIL=${ACCOUNT_EMAIL} && parse new"` but it didn't work.

Thanks,

**Comment by pavanka** [comment]
Hello Ralphilius,

Can you verify from the last 4 characters of the account key used, that this is indeed the case?
You can take a look at %HOME%/.parse/netrc file to look at the account keys you configured.
This works for me locally, so could be configuration issue on your end.

**Comment by Ralphilius** [comment]
Hello @pavanka,

The error message in cmd was that the email was not associated with the account key which is the default one.

Note that I have done `parse configure accountkey` for second account already.

Thank you,

**Comment by pavanka** [comment]
Cool, I could repro this. Perhaps the command needs to be corrected. let me check.

**Comment by pavanka** [comment]
Looks like the correct command to use is
cmd /C 'set "PARSER_EMAIL=${ACCOUNT_EMAIL}" && parse new'
It worked for me, let me know what you find. & then I can update the docs appropriately.
Thanks.

**Comment by Ralphilius** [comment]
@pavanka The command you provide got me this error:
> ''set' is not recognized as an internal or external command,
> operable program or batch file.

When I removed single quotation mark like below, the code run but choosing existing app will just showing apps from default account. I have change the `${ACCOUNT_EMAIL}` with the secondary account. 

`cmd /C set "PARSER_EMAIL=${ACCOUNT_EMAIL}" && parse new`

**Comment by pavanka** [comment]
I am not that familiar with windows command line tools. the crux is that you set this environment variable before running 'parse new', the command I pasted worked for me on powershell. I was using windows 8.

**Comment by pavanka** [comment]
i would also suggest just replacing ' with " and trying it. 
also instead of `parse new` perhaps try `parse list`, just to verify the right email is picked.

**Comment by Ralphilius** [comment]
Hello,

I can set the PARSER_EMAIL to my secondary account, but the `parse new` or `parse list` command just take the account key from the default/other account.

The error message is:
>Account key could not be used.
>Error: Account key "************************************kHs2" does not belong to
 >"email@replaced.com "

I have also tried with PowerShell on Windows 8, but got the error:
>Error talking to the Parse servers; please try again.

Does the `parse new` or `parse list` automatically take the account key associated with PARSER_EMAIL?

**Comment by pavanka** [comment]
Hey,
So afaict, this is not a cli issue, I tested this on all 3 platforms. I would suggest you open a bug report and share your details confidentially, I am almost sure it is a settings issue, so we can figure out more once more info can be provided confidentially..

Btw, parse new or parse list automatically take the account key associated with PARSER_EMAIL.

**Comment by Ralphilius** [comment]
@pavanka Where could I file a bug report and which information I need to provide?

**Comment by pavanka** [comment]
See: https://parse.com/help, there is report a bug button at the bottom.
Select ParseBug->CloudCode->CommandLineTool once you click the initial report a bug button.
please paste your %HOME%/.parse/netrc file as well as the full output of the command you are running.

**Comment by Ralphilius** [comment]
Well, it is weird. Today I gave it a try with below command after restarting my computer:

`set "PARSER_EMAIL=YOUR_EMAIL" && parse new`

It is working now.

@pavanka Should you add the windows tool in use in the docs? Like Powershell or cmd?

**Comment by pavanka** [comment]
Oh awesome! 
I think that's the command that worked for me too. It would be great if you describe your experience. (what worked on cmd & what or powershell) so I can double check that & write it in docs.

Thanks for the patience.
