### ISSUE TITLE
Error configuring accountkey with parse cli for Windows

### ISSUE THREAD

**Issue by yferro-axa** [ParsePlatform/parse-cli#40]
I'm trying to configure the account key on Windows 7 64 bits, with the parse cli but I receive this error:

C:\>parse configure accountkey -d

Input your account key or press ENTER to generate a new one.
NOTE: on pressing ENTER we'll try to open the url:
        "https://www.parse.com/account/keys"
in default browser.
Account Key: ******************************************************
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x449907]

goroutine 1 [running]:
github.com/ParsePlatform/parse-cli/parsecli.(*Login).AuthToken(0x127168c0, 0x1271c550, 0x12714d20, 0x28, 0x0, 0x0, 0x0, 0x0)
        /home/me/oss/godeps/src/github.com/ParsePlatform/parse-cli/parsecli/login.go:222 +0x287
main.(*configureCmd).accountKey(0x127168c0, 0x1271c550, 0x0, 0x0)
        /home/me/oss/godeps/src/github.com/ParsePlatform/parse-cli/configure.go:30 +0xc3
main.*configureCmd.(main.accountKey)┬Àfm(0x1271c550, 0x0, 0x0)
        /home/me/oss/godeps/src/github.com/ParsePlatform/parse-cli/configure.go:197 +0x3f
github.com/ParsePlatform/parse-cli/parsecli.func┬À004(0x127404e0, 0x1273a9a0, 0x0, 0x1)
        /home/me/oss/godeps/src/github.com/ParsePlatform/parse-cli/parsecli/runners.go:20 +0x12d
github.com/spf13/cobra.(*Command).execute(0x127404e0, 0x1273a8d8, 0x1, 0x1, 0x0, 0x0)
        /home/me/oss/godeps/src/github.com/spf13/cobra/command.go:477 +0x2b4
github.com/spf13/cobra.(*Command).Execute(0x127400d0, 0x0, 0x0)
        /home/me/oss/godeps/src/github.com/spf13/cobra/command.go:551 +0x3f7
main.main()
        /home/me/oss/godeps/src/github.com/ParsePlatform/parse-cli/main.go:98 +0x97a

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.init┬À1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 6 [chan receive]:
main.func┬À002()
        /home/me/oss/godeps/src/github.com/ParsePlatform/parse-cli/main.go:24 +0x39
created by main.main
        /home/me/oss/godeps/src/github.com/ParsePlatform/parse-cli/main.go:26 +0x13c

goroutine 11 [semacquire]:
sync.(*Cond).Wait(0x12768200)
        /usr/local/go/src/sync/cond.go:62 +0x88
io.(*pipe).write(0x127681c0, 0x12730c94, 0x3a, 0x40, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:94 +0x1e8
io.(*PipeWriter).Write(0x1273a9d0, 0x12730c94, 0x3a, 0x40, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:161 +0x52
encoding/json.(*Encoder).Encode(0x12713830, 0x6b2c20, 0x12767da0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:173 +0x123
github.com/facebookgo/jsonpipe.func┬À001()
        /home/me/oss/godeps/src/github.com/facebookgo/jsonpipe/jsonpipe.go:15 +0xaf
created by github.com/facebookgo/jsonpipe.Encode
        /home/me/oss/godeps/src/github.com/facebookgo/jsonpipe/jsonpipe.go:21 +0xdd

**Comment by yferro-axa** [comment]
It was a problem with the corporate proxy, sorry, I will close the issue.

**Comment by pavanka** [comment]
thanks for reporting this. it should not panic. I will add a check at the appropriate place. thanks.

**Comment by pavanka** [comment]
here's the commit: https://github.com/ParsePlatform/parse-cli/commit/c8e4ab8ff96da937d66a9bf842a88eef433fe058
