### ISSUE TITLE
Heroku instance creation with space in Parse app name

### ISSUE THREAD

**Issue by bradfol** [ParsePlatform/parse-cli#41]
The cli fails when trying to create a Heroku instance for a Parse app that has a space in the name. Please see example output:

```
parse new
Would you like to create a new app, or add Cloud Code to an existing app?
Type "(n)ew" or "(e)xisting": e
1:	Test App
Select an App to add to config: 1
Which of these providers would you like use for running your server code:
1) Heroku (https://www.heroku.com)
2) Parse  (https://parse.com/docs/cloudcode/guide)
Type 1 or 2 to make a selection: 1

Let's create a new Heroku app in which server code will be run.
The Heroku app will be named: "test app-o1jizu-8168"
Note that this can be changed later using Heroku API or Dashboard.

Name must start with a letter and can only contain lowercase letters, numbers, and dashes.
```

**Comment by pavanka** [comment]
ha! nice catch. heroku does not allow for an app to have spaces in its name while Parse does.
so this could be an issue. I will update the logic to overcome this.

**Comment by pavanka** [comment]
fixed in commit: https://github.com/ParsePlatform/parse-cli/commit/759ab05b05b8cc68b5b6f8a3b51e885ec71cc99d
should not be an issue in next minor release. 
Thanks for reporting this!

**Comment by bradfol** [comment]
Thanks!
