### ISSUE TITLE
Unable to download parse.exe

### ISSUE THREAD

**Issue by harrydet** [ParsePlatform/parse-cli#44]
Hi, could you check if the links are still working? I'm trying to download parse.exe but keep getting a connection timed out result. I've also tried it with cURL (and followed the redirect) but didn't have any luck that way either. This is what I'm getting:

 Failed to connect to github-cloud.s3.amazonaws.com port 443: Timed out

**Comment by pavanka** [comment]
works totally fine for me. I was able to download the exe.
perhaps you are on a very slow connection or behind a proxy?

**Comment by harrydet** [comment]
Works fine for me now too. It probably was a proxy issue. Thanks.

Closing
