### ISSUE TITLE
Uploading symbol files of Xcode fails

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [ParsePlatform/parse-cli#49]
1. Ran `parse new` inside the project directory.
2. Followed the steps and created an accountkey. I used the email of my Parse account and its password. It was successful and it pulled down the available projects I had. It created a folder called **cloud** with one JavaScript file named *main.js* inside.
3. I added the following Run Script to Xcode (v7.1).
```
export PATH=/usr/local/bin:$PATH
cd "${PROJECT_DIR}"/cloud

parse symbols -p "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"
```
Building the project fails when it's executing this script. This is the output I get.
```
We've changed the way the CLI works.
To save time logging in, you should create an account key.

Type "parse configure accountkey" to create a new account key.
Read more at: https://parse.com/docs/js/guide#command-line-account-keys
Email: Password (will be hidden): stty: stdin isn't a terminal
stty: stdin isn't a terminal

Sorry, we do not have a user with this username and password.
If you do not remember your password, please follow instructions at:
  https://www.parse.com/login
to reset your password
Please try again...
Email: Password (will be hidden): stty: stdin isn't a terminal
stty: stdin isn't a terminal

Sorry, we do not have a user with this username and password.
If you do not remember your password, please follow instructions at:
  https://www.parse.com/login
to reset your password
Please try again...
Email: Password (will be hidden): stty: stdin isn't a terminal
stty: stdin isn't a terminal

Sorry, we do not have a user with this username and password.
If you do not remember your password, please follow instructions at:
  https://www.parse.com/login
to reset your password
Command /bin/sh failed with exit code 1
```
Complete output is [here](http://pastebin.com/eAFXGjAj).

I thought it was something wrong with the accountkeys so I searched for the place where they are stored which is here, `${HOME}/.parse/netrc` according to the docs. But that directory doesn't exist in my machine either.

**Comment by pavanka** [comment]
Hey,

You should configure account keys using

`parse configure accountkey`
Just type in this command & follow steps, it will setup an account key for you, which will automatically get picked up subsequently.

**Comment by Isuru-Nanayakkara** [comment]
Should I use the email I use to log in to Parse as the accountkey? Because I tried that I got the following error even though it is my correct email.

**Sorry, the account key: "********************.com" you provided is not valid.**

**Comment by pavanka** [comment]
try `parse configure email` and type in the email corresponding to your configured account key
if that does not work. what version of cli are u using? need more details on setup.
what did you do with parse new, did u setup an existing app or create a new app, etc. also now does the netrc file look, does it have entries like
api.parse.com
api.parse.com#{youremail}.com

or just one or the other & etc.

**Comment by Isuru-Nanayakkara** [comment]
Okay, I found my problem. I thought running `parse new` created an accountkey automatically. I created one from my dashboard and added it via the CLI. Everything's working now. Thanks!

**Comment by Isuru-Nanayakkara** [comment]
Okay I hit another wall. I tested crash reporting on the simulator and the symbols get uploaded. Everything works properly.

But then I tested it on a device. The crash gets reported but I get the **This stack trace is unsymbolicated. To obtain symbols, you need to upload your dSYM file via the command line tool.** message in the dashboard.

Do I have to do anything else when I run it in the device?

**Comment by pavanka** [comment]
the issue is not a cli issue, looks like a backend issue, please report using the [bug tool](https://parse.com/help). 

looks like you are trying to use crash reporting for the first time. note that we are deprecating crash reporting, soon we will not support this feature, an email was sent to existing users, you should use ios [crash reporting](https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AnalyzingCrashReports/AnalyzingCrashReports.html) instead.
