### ISSUE TITLE
cmd 'parse develop' is sometimes stuck

### ISSUE THREAD

**Issue by rihadavid** [ParsePlatform/parse-cli#50]
I've just been asked, after calling 'parse develop' in windows command line, to update the parse command line tool and I did.
But now when I run parse develop command (or any other parse command), nothing happens, it just jumps on new empty line! I tried to delete and install new parse.exe, restart computer, nothing helps.
Please help!

**Comment by pavanka** [comment]
hey, for starters, you can try using the old version https://github.com/ParsePlatform/parse-cli/releases/tag/release_3.0.1 and ignore cli asking you to upgrade.

I could not repro it, works just fine for me.

**Comment by rihadavid** [comment]
Thank you, older version works!

**Comment by pavanka** [comment]
we should fix the bug nevertheless. can you provide repro steps, it worked just fine for me.
what shell are you using, etc. would help. could be an issue with reading from stdin afaict.

also in parse develop you could just type `parse develop --verbose` to see if it is trying to do anything.
it is not really stuck, not printing all the redundant info is all.

**Comment by rihadavid** [comment]
![bez nazvu](https://cloud.githubusercontent.com/assets/15065185/11598225/eaf5ed58-9ac0-11e5-92a1-288eb9b7e597.png)

**Comment by pavanka** [comment]
I'll take a look. so develop is the faulty one, other commands worked fine right?

**Comment by rihadavid** [comment]
Yes, I think once I had problem with parse help too, but know it seems that other commands are working. Now I ran parse update again and log is different, but still never ends:
![bez nazvu](https://cloud.githubusercontent.com/assets/15065185/11598516/a2371978-9ac2-11e5-821f-084e73cc90b6.png)

**Comment by rihadavid** [comment]
But hey, now it works if I edit the file it deploys! So I gues you should look for the problem in first picture. Maybe calling parse update multiple times just solves the problem

**Comment by pavanka** [comment]
sure, might be some transient bug related to how cmd & cli interact, still not sure. but this is expected. when u change a file it updates. if u are not seeing any other logs then. it is probably related to some ongoing backend issue.

**Comment by pavanka** [comment]
this works as expected in the cli for me. my guess is that it failed to upload files in the first paste & kept retrying to upload. not sure what the network conditions were at that time. perhaps adding a better message at that time would be more helpful, cannot repro it though.
