### ISSUE TITLE
parse deploy error

### ISSUE THREAD

**Issue by GPack1** [ParsePlatform/parse-cli#51]
On parse deploy i get the error: x509: failed to load system roots and no roots provided.
(OS Ubuntu 14.04)

**Comment by pavanka** [comment]
can you rerun that command with this option set & paste the output
`PARSE_ERROR_STACK=1 parse deploy`,
i bet it is a misconfigured os, hence I cannot repro.

**Comment by GPack1** [comment]
x509: failed to load system roots and no roots provided
/home/travis/gopath/src/github.com/ParsePlatform/parse-cli/main.go:143      checkIfSupported
/home/travis/gopath/src/github.com/ParsePlatform/parse-cli/main.go:101      main
/home/travis/.gimme/versions/go1.4.2.linux.amd64/src/runtime/proc.go:72     main
/home/travis/.gimme/versions/go1.4.2.linux.amd64/src/runtime/asm_386.s:2288 goexit

**Comment by GPack1** [comment]
Now I get this, after requesting password:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x8097025]

**Comment by pavanka** [comment]
please try this on your computer 

`curl https://api.parse.com/1/supported?version=latest`

and paste the output here. this stack trace shows that your computer was unable to authenticate api.parse.com domain using ssl. so my guess it your computer is misconfigured.

the second issue needs more stack traces pl. esp because it cannot be reproduced, would help to know what conditions this gets hit in.

**Comment by GPack1** [comment]
I solved executing an `update-ca-certificates` command. I think that certificates were broken and it stopped to work, but I dont know why. Now it works, thanks.

**Comment by igordeoliveirasa** [comment]
I'm using mac. How to solve that?

dial tcp: lookup api.parse.com on 10.0.0.1:53: cannot unmarshal DNS message
/home/travis/gopath/src/github.com/ParsePlatform/parse-cli/main.go:143        checkIfSupported
/home/travis/gopath/src/github.com/ParsePlatform/parse-cli/main.go:101        main
/home/travis/.gimme/versions/go1.4.2.linux.amd64/src/runtime/proc.go:72       main
/home/travis/.gimme/versions/go1.4.2.linux.amd64/src/runtime/asm_amd64.s:2233 goexit
