### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by Seishin** [ParsePlatform/parse-cli#52]
How to logout from the currently used account and login into a new one? 
I tried to add the new account key but it's still logged into the first account...

**Comment by Seishin** [comment]
The only way I found was to change the default account key in use with:
`parse configure accountkey -d`

This must be included in the official help and guide... I found it in the comments of the configure.go file...

**Comment by pavanka** [comment]
there is no logout, but you can delete the account key in `~/.parse/netrc`.
would you like to submit a pull request to our docs here: `https://github.com/ParsePlatform/Docs/blob/master/en/cloudcode/command-line.mdown`
