### ISSUE TITLE
parse.exe untrustworthy by Symantec

### ISSUE THREAD

**Issue by VanHumbeeckA** [ParsePlatform/parse-cli#56]
Symantec antivirus deletes the parse.exe file as soon as I download it, saying 'There is strong evidence this is file is unthrustworthy'.

**Comment by pavanka** [comment]
I am not sure if this will help.
https://support.symantec.com/en_US/article.TECH132220.html

perhaps we'll need to do this, meanwhile can u disable check for this binary?
