### ISSUE TITLE
[Windows] The client close immediately

### ISSUE THREAD

**Issue by edades** [ParsePlatform/parse-cli#57]
I download parse.exe but when i open the file this is closed immediately. i try open this as admin but i have the same result.
i use win 8.1 - core i7 - 4gb ram - 64bits

Thanks

**Comment by pavanka** [comment]
it is a plain windows executable. 
https://parse.com/docs/cloudcode/guide#command-line-windows

The Parse command line tool for Windows is available here. Download the Windows executable named: parse.exe at this link. Note that this is not an installer, it is just a plain Windows executable.

https://parse.com/apps/quickstart#cloud_code/windows

so you should put it in an accessible location. add it to your path & use it from cmd or powershell.

like open cmd & type parse, clicking it will not help.
