### ISSUE TITLE
parse deploy fails using go version 1.4.2 (on some networks)

### ISSUE THREAD

**Issue by a-hitti** [ParsePlatform/parse-cli#58]
parse deploy
dial tcp: lookup api.parse.com: no such host
/home/travis/gopath/src/github.com/ParsePlatform/parse-cli/main.go:143        checkIfSupported
/home/travis/gopath/src/github.com/ParsePlatform/parse-cli/main.go:101        main
/home/travis/.gimme/versions/go1.4.2.linux.amd64/src/runtime/proc.go:72       main
/home/travis/.gimme/versions/go1.4.2.linux.amd64/src/runtime/asm_amd64.s:2233 goexit

When I updated to go version 1.5.3 and installed the cli using:
'go get -t github.com/ParsePlatform/parse-cli'

I am able to 'parse-cli deploy'

**Comment by pavanka** [comment]
relevant thread here: https://github.com/golang/go/issues/3575
excerpt "this may be related to file descriptor exhaustion"

deploy does 64 concurrent requests at a time. perhaps that is eating into fd limits for the process.
let me bump the go version in travis script.
