### ISSUE TITLE
The CLI wants an account key from parse.com, but that's not possible

### ISSUE THREAD

**Issue by shecky2000** [ParsePlatform/parse-cli#59]
Installed Parse Server on Digital Ocean, and have been trying to use the CLI to manage cloud code. I've hit a wall, since the CLI tool will not move forward without an account key on Parse.com (which no longer offers account keys). For example, if I type in "parse new", I get this:

`We've changed the way the CLI works.  To save time logging in, you should create an account key.  Type "parse configure accountkey" to create a new account key.  Read more at: https://parse.com/docs/cloudcode/guide#command-line-account-keys`

If you actually do that, it responds:

`Input your account key or press ENTER to generate a new one.  NOTE: on pressing ENTER we'll try to open the url: "https://www.parse.com/account/keys" in the default browser:`

This leads to a login page. Since I don't have an account on Parse.com (nor should it be necessary for Parse Server), I'm stuck. If I click on the "I don't have an account" link, it just takes me to the front page.

Am I missing something or is this a legit Catch-22?  Thanks.

**Comment by pavanka** [comment]
are you sure https://www.parse.com/account/keys does not open for you? it works fine for me. hence wondering.

also parse is shutting down, so I do not think it is a good idea to be developing on cloud code now :)
please look at open source parse-server for better alternatives.

**Comment by pavanka** [comment]
my guess is that you do not have a parse account. we disallow people from creating new parse accounts. any existing customer can use create new parse account keys though.
http://blog.parse.com/announcements/moving-on/

**Comment by shecky2000** [comment]
Thanks, Pavanka. But, if the CLI requires an account key from Parse.Com--even when I've launched my own instance of Parse Server on Digital Ocean---in order to proceed, doesn't that mean we have a dead end?

**Comment by pavanka** [comment]
parse cli is useful only for deploying cloud code to parse server.
when you are running parse server code on your own servers, cli is not of much help. 

perhaps you will want to enquire in https://github.com/ParsePlatform/parse-server to know how to deploy cloud code there?
there are many generic tools and deploy mechanisms based on the infrastructure you are using to host parse server.
