### ISSUE TITLE
Updated to work with Parse Server?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-cli#62]
Will we be able to use this eventually to point to our own parse server and be able to use the cli commands such as deploy etc for cloud code?

**Comment by pavanka** [comment]
parse cli uses a bunch of custom endpoints on parse to deploy, fetch script versions, etc.
with opensource parse server everything is node. so deploys can be as simple as git push on heroku or on aws and other platforms using their deployment tools.

any work done here would just end up wrapping the native tools of those platforms.
so we decided not to go down that path.
