### ISSUE TITLE
Linking Heroku Apps to Cloud Code

### ISSUE THREAD

**Issue by corbanb** [ParsePlatform/parse-cli#63]
Hi all, I am trying to have multiple apps linked to my cloud code for testing. Is there a way to do the following?

```javascript
{
  "applications": {
    "dev": {
      "parseAppId": "asdfasdfasd",
      "herokuAppId": "adfasdg"
    },
    "_default": {
      "link": "dev"
    },
	"production": {
		"parseAppId": "asdfadfss",
		"herokuAppId": "asdfadsfasd"
	},
	"_production": {
		"link": "production"
	}
  }
}

```

I would like to be able to do:
```bash
$ parse deploy # deploys the default app
$ parse deploy production # deploys the production app
```

Right now when I run `$ parse deploy production` I get back **Heroku app is not linked** I'm guessing there must be a way to link the 2.

**Comment by pavanka** [comment]
it is not possible to link multiple parse apps to the same heroku app. it was designed to be a 1-1 link, you can trivially deploy the exact same code to your other heroku app that can act as a staging/testing app.

this is similar to how people use two parse apps one for production and one for testing currently.

**Comment by corbanb** [comment]
@pavanka I want 1 cloud code app to 2 parse instances tho. Is that not possible?
