### ISSUE TITLE
parse-cli for local parse-server

### ISSUE THREAD

**Issue by abubobe** [ParsePlatform/parse-cli#64]
hi,

how to configure this parse-cli to connect to my local parse-server instead of parse.com?

**Comment by pavanka** [comment]
hi @abubobe please refer to https://github.com/ParsePlatform/parse-cli/issues/62

you can use the awesome node tools to deploy code to your local server.
`parse develop` can be simulated by nodemon https://codeforgeek.com/2014/09/update-code-without-restarting-node-server/
in general deploying is just a matter of restarting your node server on code update.
all the remaining cli commands can also be realized using node tools.
