### ISSUE TITLE
Deploy failed with error --- macOS Sierra issue?

### ISSUE THREAD

**Issue by sudochownrwhoami** [ParsePlatform/parse-cli#66]
> Deploy failed with error:
> internal error
> Will retry in 0 seconds.

I am getting the above error when attempting to deploy my updated cloud code on macOS Sierra. Anyone having similar issues?

**Comment by pavanka** [comment]
it looks like a server-side issue.

can you please retry with
`PARSE_ERROR_STACK=1 parse deploy ...`

and then open a bug with parse https://developers.facebook.com/bugs/
pasting the stack trace there. also letting us know what app this is about.
