### ISSUE TITLE
Store CloudCode credentials in secure storage

### ISSUE THREAD

**Issue by jeroenleenarts** [ParsePlatform/parse-cli#7]
The API key and APP ID are fine to share/store publicly. But the master key is stored in the Cloud project's global.son in clear text. Considering the powers associated with the master key, I think it's better to store such an item outside of the source path.

How about storing the sensitive master key in an external secure storage?
Such as the Keychain for OSX, Credential Locker for Windows 8 and later and Linux Secret Service.

Finding or creating an API like KeyRing for Python would be helpful.

**Comment by pavanka** [comment]
that is indeed a great idea. i am working on such a feature already.
do you think personal access tokens (much like github: https://github.com/blog/1509-personal-api-tokens) is good enough?

**Comment by jeroenleenarts** [comment]
I suppose.

Right now I have two concerns that I think should be addressed.

Taking the credential(s) out of the project source path.
Storing the credential(s) securely.

If the credential is scoped or bound to a single login that would be great. Especially if this is also used server side for audit logging of changes performed on a parse.com app.

Right now when someone breaks something they can get away with it by plain denial. Malicious intent is even scarier if someone has access to root (master key) on an app.

**Comment by pavanka** [comment]
both comments will be addressed in 2 diffs.

there will be just one user scoped token stored in ~/parse/.netrc that can be used to perform deploys or create apps

as far as storing & logging, unfortunately to maintain backward compatibility, we must allow users to deploy with a master key, and also allow existing parse projects to continue to work.

mid next week, we'll enable the  "access tokens" functionality.

then later this month, well have a new way of storing config information. that's a big refactor & should still maintain backward compatibility to existing codebases.

**Comment by jeroenleenarts** [comment]
Alright, if you would like me to review or try a branch, let me know. Very interested in this change. :) Testing with these projects:

- https://github.com/CocoaHeadsNL/CocoaHeadsNL-iOS
- https://github.com/sebastiaanschool/sebastiaanschool-iOS
- A private event schedule app

**Comment by pavanka** [comment]
Here's the huge patch: 
https://github.com/ParsePlatform/parse-cli/pull/18

I would suggest that you pull this from here: https://github.com/pavanka/parse-cli/tree/new_config
and the try out the new config format. it will not store master key anymore

1) try the new build on your existing project:
   * add a new app to the code using "parse add", u'll see master key is not added for it
   * try to run the new build normally, like deploy, etc. for apps whose master key is still present in config
     now, manually remove the master key & try to deploy, etc. u'll see that master key is not needed anymore.
2) try to create a new project using "parse new" & see that new config formats are now present.

**Comment by pavanka** [comment]
2.2.4 solves the problem related to cli.
