### ISSUE TITLE
would you consider to have a command line which to pull projects from server

### ISSUE THREAD

**Issue by wahengchang** [ParsePlatform/parse-cli#9]
would you consider to have a command line which to pull projects from server

thanks

**Comment by pavanka** [comment]
in the works. we'll soon have a pull request for that.

**Comment by pavanka** [comment]
here's the relevant pull request fyi: https://github.com/ParsePlatform/parse-cli/pull/13

**Comment by pavanka** [comment]
this should now be possible in the next release.
committed in master now.
